version: "3.8"

services:
  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "8000:8000"
    networks:
      - app_net

  client:
    build:
      context: ./client
    container_name: client
    depends_on:
      - server
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
