apiVersion: v1
kind: Pod
metadata:
  name: init-container-example
spec:
  initContainers:
  - name: init-db
    image: busybox
    command: ['sh', '-c', 'echo Initializing database...']
  containers:
  - name: main-app
    image: nginx
